### ISSUE TITLE
the function “sample()” should be rename

### ISSUE THREAD

**Issue by wangjiaxuan666** [fgcz/rawrr#22]
Hi, Thankful for your great work to support the useful R packages, But the sample() is a import function in R base. Many R script and packages base on the "sample()" function. If you can rename the example database function like "example()" . IT will help researcher use more fluently.

Thanks for you grateful work for R packages“rawR”

**Comment by cpanse** [comment]
@wangjiaxuan666 thank you for your feedback. I use base R sample myself. we will rename it asap.

**Comment by cpanse** [comment]
@tobiasko How do we want to name this function?

**Comment by cpanse** [comment]
DONE
