### ISSUE TITLE
display sublicense at startup of interactive R session

### ISSUE THREAD

**Issue by tobiasko** [fgcz/rawrr#26]
The following should be displayed after loading the package:

```
RawFileReader reading tool. Copyright © 2016 by Thermo Fisher Scientific, Inc. All rights reserved
```

**Comment by cpanse** [comment]
@tobiasko 
![Screenshot 2020-12-10 at 19 57 00](https://user-images.githubusercontent.com/4901987/101816953-ff699080-3b21-11eb-8937-a44a9715d215.jpg)

**Comment by cpanse** [comment]
[RawFileReaderLicense.pdf](https://github.com/fgcz/rawrr/files/5675089/RawFileReaderLicense.pdf)

**Comment by tobiasko** [comment]
What just came to my mind. Are their different versions of the RawFileReader? Shouldn't that be displayed after `using`? Like

```
...using
RawFileReader 1.0.0
RawFileReader reading tool. Copyright © 2016 by Thermo Fisher Scientific, Inc. All rights reserved
```

**Comment by cpanse** [comment]
@

> What just came to my mind. Are their different versions of the RawFileReader? Shouldn't that be displayed after `using`? Like
> 
> ```
> ...using
> RawFileReader 1.0.0
> RawFileReader reading tool. Copyright © 2016 by Thermo Fisher Scientific, Inc. All rights reserved
> ```

we add the version number in the package information (NEWS file)
