### ISSUE TITLE
Spectrum scan centroid mZ, intensity and noises values do not match

### ISSUE THREAD

**Issue by JorgeVindelAlfageme** [fgcz/rawrr#53]
Hi:
I'm using "rawrr" to read and represent 2 spectrum scans. With the first scan, I had no problems when using the plot function to represent "spectrum.scan$centroid.mZ" values on the x axis, and "spectrum.scan$centroid.intensity" and" spectrum.scan$noises" as a rate on the y axis: The plotted spectrum is the same as the expected spectrum in this case, considering the obtained results with another software to represent them. However, with the second one, the plotted image is different as the expected one. I think that this is due to that mZ, intensity and noises vectors differ in length for this second scan. How can I approach this situation? How is it possible that these vector lengths differ? In the first scan, this wasn't the case.
Thank you for your time.

**Comment by cpanse** [comment]
can you please provide your code snippet and raw file?

**Comment by JorgeVindelAlfageme** [comment]
Hi again:
Since it's been one year and three months since the moment I posted the question, it's not necessary anymore to answer it. I used another Python library to handle the data.
Regards.
