### ISSUE TITLE
Error in Example: Length of "x" and "y" are not matching

### ISSUE THREAD

**Issue by DRiXD** [fgcz/rawrr#54]
Hi everyone, 
to test this package I wanted to load the .raw file and follow the provided example code.
Somehow my R sends me an error message that the "x and "y" coordinates are not matching:
<img width="765" alt="Bildschirmfoto 2022-07-21 um 22 46 14" src="https://user-images.githubusercontent.com/39619011/180312163-8f536867-dc93-4e3b-bfa1-c53bffd15eed.png">

Now when I run I get:
```
> plot(S[[1]], centroid=TRUE)
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  Length of 'x' and 'y' do not match
```

I have absolutly no Idea what I'm doing wrong and am super lost.
I would appreciate some help here!

Also I am new to R and working with bio-informatics data so if anyone could provide any help how to come up with the number in the scan vector (paper just mentions some database seach?) that would be awesome aswell.
Thanks in advance!

**Comment by DRiXD** [comment]
Oh and if it's necessary for debug issues:
<img width="327" alt="Bildschirmfoto 2022-07-21 um 22 50 35" src="https://user-images.githubusercontent.com/39619011/180312935-172064ee-71dc-4113-ad3c-659a2c75cb9c.png">
 And R-version 4.2.1

**Comment by tobiasko** [comment]
That is most likely due to your OS settings regarding your decimal sep. character. The Thermo API expects `.`, not `,`. see for instance

https://answers.microsoft.com/en-us/msoffice/forum/all/changing-decimal-separator-from-comma-to-dot/953556fb-00d0-45ad-bd4f-6ca8afa5025a

for Windows.

**Comment by tobiasko** [comment]
Did the above solve your problem @DRiXD?
