### ISSUE TITLE
Read noise value for profile mode mass spectra

### ISSUE THREAD

**Issue by Taoq888** [fgcz/rawrr#56]
First the rawrr package is so amazing, which will greatly facilitate my data analysis. I have now realized that I cannot extract the Resolution R, noise, and charge z values from my own data. 
At the begining, I thought it could be that our instrument is LTQ Orbitrap Velos, which is slightly different with the one QE in the paper. While, I found the noise can be read when a centroid mass spectrum as an input. So seems it can't access to the noise values in the profile mode mass data. I am wondering if it is possible to obtain these values, as this information is present in the raw data.

![image](https://user-images.githubusercontent.com/82729748/191081024-1d255808-abfb-4604-902d-1eafe70bc9be.png)
for the centriod mass spectrum

![image](https://user-images.githubusercontent.com/82729748/191081194-4c981495-9728-4290-a171-5cd65db0650b.png)
for the profile mass spectrum

same mass spectrometer is used to obtain these data. (LTQ Orbitrap velos)

Thank you very much!

**Comment by tobiasko** [comment]
Hi @Taoq888,

that is true. For reduced profile mode (FTMS + p) the noise values a written to a different slot (stream). But @cpanse recently made some changes to our code so these can also be accessed. But these changes haven't made it to a stable package release yet.

**Comment by tobiasko** [comment]
Please try this one here: https://github.com/fgcz/rawrr/issues/37#issuecomment-1241155140

**Comment by cpanse** [comment]
or  installed via
`install.packages("https://fgcz-ms.uzh.ch/~cpanse/rawrr/rawrr_1.5.3.tar.gz", repo = NULL)`

**Comment by Taoq888** [comment]
> or install via `install.packages("https://fgcz-ms.uzh.ch/~cpanse/rawrr/rawrr_1.5.3.tar.gz", repo = NULL)

Thank you for your reply. Yes, I have tried this verison, and I still can not get the noise information. It is still cool to direct read intensity data using this amazing package. Thank you very much!!
