### ISSUE TITLE
Problem executing readChromatogram inside Singularity container

### ISSUE THREAD

**Issue by toniher** [fgcz/rawrr#63]
Hello,

I am trying to execute ``rawrr::readChromatogram`` inside a Singularity container (r-ver:4.1), concretely this command:
```
QCfile <- rawrr::readChromatogram( rawfile = args[1], mass = 566.83, tol = 10, type = "xic", filter = "ms", tmpdir="./tmp")
```
and I am getting this error, and after debugging a bit:

```
Error in .rawrrSystem2Source(rawfile, input = mass, rawrrArgs = procArgs,  :
  Rcode file to parse does not exist. '/home/toniher/.cache/R/rawrr/rawrrassembly/rawrr.exe' failed for an unknown reason.
Please check the debug files:
        ./tmp/file231265115b740c.stderr
        ./tmp/file231265636edd0f.stdout
and the System Requirements
Calls: <Anonymous> -> .rawrrSystem2Source
Execution halted
```
checking stderr I see the following error:

``
failed to catch configfile and itol
``

I can confirm trying to run straight the mono executable:
```
/usr/bin/mono '/home/toniher/.cache/R/rawrr/rawrrassembly/rawrr.exe' '2022ZZ999_bovine.raw' xic 10.000000 'ms' './tmp/file2312652e2acf2f.txt' './tmp/file2312651aaea3c0.R'
```

Do you have any idea what might be failing?

**Comment by cpanse** [comment]
Good morning; 

Two things:
1. if possible use the latest R4.3.x and rawrr 1.8.1 https://github.com/fgcz/rawrr/ and run `rawrr::installRawrrExe()` 

2. it is possible that you don't have writing permission to the tmp folder? 
the error msg comes from here: 
- https://github.com/fgcz/rawrr/blob/5541dc422eecb59b0fb2211bfa364264f4ba505a/inst/rawrrassembly/rawrr.cs#L827C31-L827C31
- and https://github.com/fgcz/rawrr/blob/5541dc422eecb59b0fb2211bfa364264f4ba505a/R/rawrr.R#L98C37-L98C37 #64


3. Lets have a quick debug zoom session, e.g., in the afternoon?
Thanks,
C

**Comment by cpanse** [comment]
@toniher this package version will print an error message 
https://fgcz-ms.uzh.ch/~cpanse/rawrr/rawrr_1.9.1.tar.gz
can you please give it a try

**Comment by toniher** [comment]
Hi @cpanse I tried with your last package and R 4.3 version and I don't see more error messages.
Exe used is: https://github.com/fgcz/rawrr/releases/download/1.7.10/rawrr.1.7.10.exe

In tmpdir I generate these three files:
 file24146e21249eda.stderr   file24146e5f85e384.stdout   file24146e6d12a90f.txt

In txt file ```566.83``` is printed.

I cannot share screen in Zoom today, but I can arrange for tomorrow afternoon if fine with you, let's say, around 16, if fine with you.

**Comment by cpanse** [comment]
> Hi @cpanse I tried with your last package and R 4.3 version and I don't see more error messages. Exe used is: https://github.com/fgcz/rawrr/releases/download/1.7.10/rawrr.1.7.10.exe
> 
> In tmpdir I generate these three files:  file24146e21249eda.stderr  file24146e5f85e384.stdout  file24146e6d12a90f.txt
> 
> In txt file `566.83` is printed.
> 
> I cannot share screen in Zoom today, but I can arrange for tomorrow afternoon if fine with you, let's say, around 16, if fine with you.

1600 (Berlin time zone) is fine.
C

**Comment by toniher** [comment]
We were missing in our setup (Ubuntu 22.04) ``libmono-system-data4.0-cil`` as pointed in in https://github.com/fgcz/rawrr/blob/devel/INSTALL
