### ISSUE TITLE
Installation of DLLs deletes exe

### ISSUE THREAD

**Issue by leoschwarz** [fgcz/rawrr#77]
When installing the DLLs after the exe, the executable gets deleted. This can be confusing.

https://github.com/fgcz/rawrr/blob/1667b6d3eb3e6d054ee68521352b30839cb4d7d6/R/dotNetAssembly.R#L193-L199

**Comment by tobiasko** [comment]
Can? This is totally confusing... and I honestly don't know why this is done. @cpanse Can you clarify?
